version: 2
updates:
  - package_manager: "go:modules"
    directory: "/"
    schedule:
      interval: "weekly"    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"    
