---
name: Update Docs

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    name: Update Docs
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Docs
        run: ./build/inspect docs

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore(docs): regenerated docs'
          signoff: false
          title: 'chore(docs): regenerated docs'
