name: Build and test Go
on: [pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "go.mod"

      - name: Check out source code
        uses: actions/checkout@v2

      - name: Build
        run: make build

      - name: Test
        run: make test
